const Classes = [
  {
    value: "arcanista",
    label: "Arcanista",
    vida_inicial: 8,
    vida_por_nivel: 2,
    mana_por_nivel: 6,
  },
  {
    value: "barbaro",
    label: "Bárbaro",
    vida_inicial: 24,
    vida_por_nivel: 6,
    mana_por_nivel: 3,
  },
  {
    value: "bardo",
    label: "Bardo",
    vida_inicial: 12,
    vida_por_nivel: 3,
    mana_por_nivel: 4,
  },
  {
    value: "bucaneiro",
    label: "Bucaneiro",
    vida_inicial: 16,
    vida_por_nivel: 4,
    mana_por_nivel: 3,
  },
  {
    value: "cacador",
    label: "Caçador",
    vida_inicial: 16,
    vida_por_nivel: 4,
    mana_por_nivel: 4,
  },
  {
    value: "cavaleiro",
    label: "Cavaleiro",
    vida_inicial: 20,
    vida_por_nivel: 5,
    mana_por_nivel: 3,
  },
  {
    value: "clerigo",
    label: "Clérigo",
    vida_inicial: 16,
    vida_por_nivel: 4,
    mana_por_nivel: 5,
  },
  {
    value: "druida",
    label: "Druida",
    vida_inicial: 16,
    vida_por_nivel: 4,
    mana_por_nivel: 4,
  },
  {
    value: "guerreiro",
    label: "Guerreiro",
    vida_inicial: 20,
    vida_por_nivel: 5,
    mana_por_nivel: 3,
  },
  {
    value: "inventor",
    label: "Inventor",
    vida_inicial: 12,
    vida_por_nivel: 3,
    mana_por_nivel: 4,
  },
  {
    value: "ladino",
    label: "Ladino",
    vida_inicial: 12,
    vida_por_nivel: 3,
    mana_por_nivel: 4,
  },
  {
    value: "lutador",
    label: "Lutador",
    vida_inicial: 20,
    vida_por_nivel: 5,
    mana_por_nivel: 3,
  },
  {
    value: "nobre",
    label: "Nobre",
    vida_inicial: 16,
    vida_por_nivel: 4,
    mana_por_nivel: 4,
  },
  {
    value: "paladino",
    label: "Paladino",
    vida_inicial: 20,
    vida_por_nivel: 5,
    mana_por_nivel: 3,
  },
];

export { Classes };
